[summary]
    # name of this experiment
    name = 'tsinghua_dataset'
    author = 'Zhihua Liang'
    discription = 'make pet time dataset from raw datas'
    # root directory of the project (for saveing logs, models, temp files, etc...)
    project_root = '/home/zhihua/data/work_space/tsinghua'
[deepspace]
    # root directory of the dataset
    # dataset_root = '/home/zhihua/data/contest/tsinghua/new'
    dataset_root = '/home/zhihua/data/contest/tsinghua/problem'
    # data patern
    # data_patern = '**/final-*'
    data_patern = '**/problem*'
    # raw_data_format
    raw_data_format = 'h5'
    # target datatype, target normalize...
    target_data_type = 'float32'
    # output format; png or tif or npy
    data_format = 'npy'
    # data range
    # momentum min, max, mean: 0.06296406416368386, 10.498537617696288, 5.487593904471561,
    p_range = [0.0, 12.0]
    # waveform min, max, mean : 33, 927, 920.8569558668031
    waveform_range = [0.0, 950.0]
    # image size
    # size = [43212, 1000]
    # max length
    # data_size = 30000
