[summary]
    # name of this experiment
    name = 'bone_data_to_npy'
    author = 'Zhihua Liang'
    discription = 'bone reconstruction data to npy format'
[deepspace]
    # root directory of the project (for saveing logs, models, temp files, etc...)
    project_root = '/home/zhihua/data/work_space/bone'
    # root directory of the dataset
    dataset_root = '/home/zhihua/data/impainting/bone_reconstruction/yves_2020_10_21/tif'
    # dataset_root = '/home/zhihua/data/impainting/bone_reconstruction/temp/tif'
    # npy file root
    npy_root = '/home/zhihua/data/impainting/bone_reconstruction/yves_2020_10_21/npy'
    # npy_root = '/home/zhihua/data/impainting/bone_reconstruction/temp/npy'
    # target datatype, target normalize...
    data_type = 'float32'
    normalization = true
    # source format
    source_data_format = 'tif'
    # output format; png or tif or npy
    target_data_format = 'npy'
    # data transpose
    transpose = false

