[summary]
    # name of this experiment
    name = 'tpu_npy_sit3d_aligned'
    author = 'Zhihua Liang'
    discription = 'Train bone on TPU'
    # root directory of the project (for saveing logs, models, temp files, etc...)
    project_root = '/home/zhihua/data/work_space/bone'    
[deepspace]
    ########### agent ###########
    # agent name
    agent = 'deepspace.agents.bone.sit3d_tpu_random_data.Agent'
    # which device to use, can be 'gpu', 'tpu', or 'cpu'
    device = 'cpu' 
    # distribute setting
    world_size = 1 
    # random seed
    seed = 999     
    # Learning rate, can be a float number like 0.001 or a list, like [0.1, 0.001, 1e-6]
    learning_rate = 1e-1
    # scheduler
    T_0 = 10
    T_mult = 3
    # max epoches to for training.
    max_epoch = 200
    # mode = 'train', 'test', 'validate', 'real'. With 'real', no ground_truth iamges are presented
    mode = 'test'

    ######## dataset ############
    # root directory of the dataset
    train_dataset = ['/home/zhihua/ssd/npy/aligned_LQ.npy', '/home/zhihua/ssd/npy/aligned_HQ.npy']
    # load into memory before distributing
    shared_dataset = true
    # data set length
    train_data_length = 65536
    validate_data_length = 4096       
    # batch
    train_batch = 64
    validate_batch = 64    
    # data resolution
    image_size = [64, 64, 64]
    # channels
    image_channels = 1
    # tpu dataloader options
    drop_last = true
    shuffle = false
    # output format; png or tif
    data_format = 'npy'
    # workers for dataloader
    data_loader_workers = 16

    ########## model ############
    # validate every x epoches
    validate_step = 1
    # save model every x steps
    save_model_step = 5
    # checkpoint file name
    checkpoint_file = 'checkpoint.pth.tar'
    # super parameters
    patch_size = 8
    rotation_node = 4
    contrastive_head = 512
    dim = 768
    depth = 8
    heads = 12
    pool = 'cls'
    in_channels = 1
    dim_head = 32
    dropout = 0.0
    emb_dropout = 0.0
    scale_dim = 4

    ##### test ######
    test_train_dataset = '/home/zhihua/ssd/npy/aligned_LQ.npy'
    test_target_dataset = '/home/zhihua/ssd/npy/aligned_HQ.npy'
    test_batch = 64
    test_output = '/home/zhihua/data/work_space/bone/tpu_npy_sit3d_aligned_test/aligned.npy'
    data_shape = [1591, 780, 780]

[common]
    distribute = false
    # log level, can be INFO, WARNING, ERROR..., see python logging
    log_level = 'INFO'



