[summary]
    # name of this experiment
    name = 'AnimeGAN'
    author = 'Zhihua Liang'
    discription = 'AnimeGAN to transfer a video to anime'
    # root directory of the project (for saveing logs, models, temp files, etc...)
    project_root = '/home/zhihua/work'    
[deepspace]
    # Config
    # input path
    # input_path = '/home/zhihua/data/video/input/'
    input_path = '/home/zhihua/data/video/temp/'
    # 原始视频的路径
    original_video = ''
    # 提取视频图像的存放地址
    original_video_img = '/home/zhihua/data/video/image/video_img/'
    # 动漫化的图像存放地址
    anime_video_img = '/home/zhihua/data/video/image/video_anime_img/'
    # 高清化的图像存放地址
    high_video_img = '/home/zhihua/data/video/image/video_high_img/'
    # output path
    # output_path = '/home/zhihua/data/video/output/'
    output_path = '/home/zhihua/data/video/temp/'
    # 视频最终输出的路径
    output_video = ''
    # 分辨率 [960, 540], [480, 270], [1920, 1080], [1280, 720] [1269, 540]
    # resolution = [1269, 540]
    # resize
    resize = 540
    # # 目标视频的帧率 实际用不到
    fps = 0
    # 目标视频的起始时间和结束时间
    start_time = 0
    end_time = 0
    # 目标视频的分辨率 [3840, 2160], [1920, 1080], [960, 540], [480, 270]
    # target_resolution = [1920, 1080]
    # 模型的路径
    # 动画优化模型
    model_path = '/home/zhihua/data/model/real_ESRGAN/RealESRGAN_x4plus_anime_6B.pth'
    # 通用模型
    # model_path = '/home/zhihua/data/model/real_ESRGAN/RealESRGAN_x4plus.pth'
    # 预训练的模型名字 face_paint_512_v2, paprika, celeba_distill
    pretrained = 'paprika'

    # 使用的设备
    device = 'xla'
    # device = 'cpu'
    # batch for anime
    anime_batch = 16
    # batch for high resolution
    hs_batch = 1
    # shuffle
    shuffle = false
    # number of workers
    num_workers = 8
    # seed
    seed = 999
    # drop last
    drop_last = true

    # 是否使用动画化
    anime = false
    # 是否使用高清化
    high_resolution = true
    # 放大倍数
    scale = 4

    # 是否添加水印
    watermark = true
    # 水印的路径
    watermark_path = '/home/zhihua/data/video/assets/logo.png'

[common]
    distribute = true
    # log level, can be INFO, WARNING, ERROR..., see python logging
    log_level = 'INFO'


