[summary]
    # name of this experiment
    name = 'gan3d_simple_tpu_break_210_epoch_grad_disaapear'
    author = 'Zhihua Liang'
    discription = 'Train wp8 on TPU'
    # root directory of the project (for saveing logs, models, temp files, etc...)
    project_root = '/home/zhihua/data/work_space/wp8'
[deepspace]
    ########### agent ###########
    # agent name
    agent = 'deepspace.agents.wp8.gan3d_simple_tpu.Agent'
    # device config
    # which device to use, can be 'gpu', 'tpu', or 'cpu'
    device = 'cpu'    
    fp16 = false
    cpu = false    
    # distribute setting
    world_size = 8
    # random seed
    seed = 999
    # Learning rate, can be a float number like 0.001 or a list, like [0.1, 0.001, 1e-6]
    gen_lr = 1e-1
    dis_lr = 2e-1
    # 每训练n（n>=1）次Discriminator，训练一次Generator；
    gen_epoch = 3
    # scheduler
    scheduler = 'WarmupAndExponentialDecayScheduler'
    scheduler_divisor = 5
    scheduler_divide_every_n_epochs = 20        
    # image loss and dis loss weight
    loss_weight = 0.999   
    # max epoches to for training.
    max_epoch = 300
    # save ouput on first n images during validation
    save_images = [0, 1]
    # mode = 'train', 'test', 'validate'
    # mode = 'train'
    mode = 'test'

    ######## dataset ############
    # root directory of the dataset
    train_dataset = '/home/zhihua/ssd/anomaly/wp8/cyl9_npy'
    # data set length   
    split_rate = 0.99
    # batch
    train_batch = 64
    validate_batch = 16
    # channels
    image_channels = 1   
    # data resolution
    image_size = [64, 64, 64]
    # data argument, probability to break the sample
    break_range=[[0.1, 0.3], [0.1, 0.3], [0.1, 0.3]]
    break_probability = 0.5
    # dataloader options
    drop_last = true
    shuffle = false
    # output format; png or tif
    data_format = 'npy'      
    # workers for dataloader
    data_loader_workers = 16
    
    ########## model ############
    # save model every x steps
    save_model_step = 3
    # checkpoint file name
    checkpoint_file = 'checkpoint.pth.tar'

    leak_value = 0.1
    # generator model
    gen_encoder_sizes = [8, 32, 128]
    gen_temporal_strides = [2, 2, 1]    
    gen_fc_sizes = [64]
    # discriminator model
    bias = false

    ##### test ######
    # test_dataset = '/home/zhihua/ssd/anomaly/wp8/cyl9_npy_test'
    test_dataset = '/home/zhihua/ssd/anomaly/wp8/cyl8_npy_test'
    test_batch = 8
    # test_output_dir = '/home/zhihua/data/work_space/wp8/test_gan3d'
    test_output_dir = '/home/zhihua/data/work_space/wp8/test_gan3d_cyl8'


[common]
    distribute = false



