[summary]
    # name of this experiment
    name = 'dqn'
    author = 'Zhihua Liang'
    discription = 'Defect detection for POL 2020, reinforcement model'
[settings]
    # root directory of the project (for saveing logs, models, temp files, etc...)
    project_root = '/home/zhihua/data/work_space'
    # CAD object path
    mesh_file_path = '/home/zhihua/data/mesh/common/bunny/bunny_watertight.stl'
    # agent name
    agent = 'deepspace.agents.reinforcement.dqn.DQNAgent'
    # which device to use, can be 'gpu', 'tpu', or 'cpu'
    device = 'gpu'
    # retry times to break the object
    gpu_device = 0
    # angle range
    batch_size = 32
    # random seed
    seed = 999
    # Learning rate, can be a float number like 0.001 or a list, like [0.1, 0.001, 1e-6]
    learning_rate = 1e-4
    gamma = 0.999
    eps_start = 0.9
    eps_end = 0.05
    eps_decay = 200
    target_update = 10
    num_classes = 2
    memory_capacity = 10_000
    num_episodes = 50
    screen_width = 600
    # model parameters
    conv_filters = [ 16, 32, 32 ]
    # max epoches to for training.
    max_epoch = 300
    # validate every x epoches
    validate_step = 2
    # save model every x steps
    save_model_step = 2
    # checkpoint file name
    checkpoint_file = 'checkpoint.pth.tar'
    # dataloader name
    data_loader = 'defect_image_dataloader'
    # workers for dataloader
    data_loader_workers = 8
    # data resolution
    image_resolution = [512, 512]
    # channels
    input_channels = 3
    data_mode = ""
    data_folder = ""
    x_train = ""
    y_train = ""
    x_valid = ""
    y_valid = ""
    x_test = ""
    y_test = ""
    # mode = 'train', 'test', 'validate', 'metrics'
    # mode = 'train'
    # mode = 'test'
    mode = 'metrics'
    # save ouput on first n images during validation, should be smaller than batch size
    save_images = [0, 10]
    # defect detection threshold, image threshold is the range of the image and area threshold is the cut on area of defect 
    image_threshold = [0.2, 0.8]
    area_threshold = 500
    # noise level for metrics
    gaussian_noise = true
    gaussian_mean = 0
    gaussian_std = 0.1



