[summary]
    # name of this experiment
    name = 'dqn_xray'
    author = 'Zhihua Liang'
    discription = 'Defect detection for POL 2020, reinforcement model'
    # root directory of the project (for saveing logs, models, temp files, etc...)
    project_root = '/home/zhihua/data/work_space'
[dxray]
    # this is settings for environemnt for deep reinforcemnet training.
    # setting for xray environment
    # CAD object path
    mesh_file_path = '/home/zhihua/data/mesh/common/bunny/bunny_watertight.stl'
    # is the CAD object watertight?
    watertight_cad = false  
    # retry times to break the object
    retry = 10
    # angle range
    angle_range = [ [ -3, 3 ], [ -3, 3 ], [ 0, 360 ] ]              
    # source distance from the origin point
    source_distance = -40
    # detector distance from the origin point
    detector_distance = 960
    # pixel size of detector
    pixel_size = [0.6, 0.6]
    # resolution of detector
    resolution = [ 512, 512 ]    
    # removed part radius range
    radius_range = [0.01, 0.1]
    # removed part removed vertices range
    remove_range = [0.01, 0.1]
    # removed part unit, can be 'scale' for object scale or 'voxel' for voxel size.
    unit = 'scale'
    # if showing preview
    interactive = false    
    # detection model
    model_path = '/home/zhihua/data/work_space/defect_gan_train_on_astra_dataset/checkpoints/20_checkpoint.pth.tar'
    # defect detection threshold, image threshold is the range of the image and area threshold is the cut on area of defect 
    image_threshold = [0.2, 0.8]
    area_threshold = 500    
    # max steps per episode
    max_step = 3
[deepspace]
    # CAD object path
    mesh_file_path = '/home/zhihua/data/mesh/common/bunny/bunny_watertight.stl'
    # agent name
    agent = 'deepspace.agents.reinforcement.dqn.DQNAgent'
    # which device to use, can be 'gpu', 'tpu', or 'cpu'
    device = 'gpu'
    gpu_device = 0
    # angle range
    batch_size = 32
    # random seed
    seed = 999
    # Learning rate, can be a float number like 0.001 or a list, like [0.1, 0.001, 1e-6]
    learning_rate = 1e-4
    gamma = 0.999
    eps_start = 0.9
    eps_end = 0.05
    eps_decay = 200
    target_update = 10
    num_classes = 1
    memory_capacity = 1000
    num_episodes = 50
    screen_width = 600
    # model parameters
    conv_filters = [ 16, 32, 32 ]
    # max epoches to for training.
    max_epoch = 300
    # validate every x epoches
    validate_step = 2
    # save model every x steps
    save_model_step = 2
    # checkpoint file name
    checkpoint_file = 'checkpoint.pth.tar'
    # dataloader name
    data_loader = 'defect_image_dataloader'
    # workers for dataloader
    data_loader_workers = 8
    # data resolution
    image_resolution = [512, 512]
    # channels
    input_channels = 3
    data_mode = ""
    data_folder = ""
    x_train = ""
    y_train = ""
    x_valid = ""
    y_valid = ""
    x_test = ""
    y_test = ""
    # mode = 'train', 'test', 'validate', 'metrics'
    # mode = 'train'
    # mode = 'test'
    mode = 'metrics'
    # save ouput on first n images during validation, should be smaller than batch size
    save_images = [0, 10]
    # noise level for metrics
    gaussian_noise = true
    gaussian_mean = 0
    gaussian_std = 0.1
    # gan model parameters
    num_filt_g = 64
    num_filt_d = 64
    relu_slope = 0.2
    latent_space_size = 1024
    # channels
    image_channels = 1


